# Generated by Django 4.2.16 on 2024-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0002_remove_product_price_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='photo',
            field=models.ImageField(blank=True, help_text='Lisää tuote kuva', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Lisää tuotteen nimi', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='detail',
            field=models.CharField(help_text='Lisää tuotteen tarkempi kuvaus', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Lisää tuotteen hinta', max_digits=8),
        ),
    ]
