# Generated by Django 4.2.16 on 2024-11-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0003_productdetail_photo_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='photo',
            field=models.ImageField(blank=True, help_text='Lisää tuotekuva', null=True, upload_to='images/'),
        ),
    ]
