# Generated by Django 4.2.16 on 2024-11-29 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0004_alter_productdetail_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(help_text='Lisää arvostelu', max_length=300)),
                ('stars', models.PositiveSmallIntegerField(help_text='Anna tähtiä (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verkkokauppa.product')),
            ],
        ),
    ]
