# Generated by Django 4.2.16 on 2024-11-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='price',
        ),
    ]
