# Generated by Django 4.2.16 on 2024-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0007_alter_productdetail_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lisää tuotteen hinta', max_digits=8),
            preserve_default=False,
        ),
    ]
