# Generated by Django 4.2.16 on 2024-11-30 00:08

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=now),
        ),
    ]
