# Generated by Django 4.2.16 on 2024-11-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0009_product_date_added_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
