# Generated by Django 5.1.4 on 2024-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0013_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Lisää tuotekuva', null=True, upload_to='images/'),
        ),
    ]
