# Generated by Django 5.1.4 on 2024-12-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verkkokauppa', '0016_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
